{{- if .Values.siteConfig.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frappe.appName" . }}-site-config
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  site_config_values.json: |
{{ .Values.siteConfig.values | toPrettyJson | indent 4 }}
{{- end }}
