# App name — used for deployment name, service name, labels, httproute
app:
  name: pass-values

# Namespace
namespace: pass-values

redis:
  cache: "redis://server-ip:6385"

# Image
image:
  repository: harbor.asakta.cloud/test/survey
  digest: "sha256:5de9c5d65a96ef9f95e5d57b3f1cd9bb99829accea6be73844017327584c8871"
  pullPolicy: IfNotPresent

# Site config
site:
  name: pass-values

# PVC
persistence:
  claimName: pass-values

# Gateway
gateway:
  name: pass-values
  namespace: pass-values
  hostname: pass-values

siteConfig:
  enabled: true
  values:
    gis_user: ""
    gis_password: ""
    gis_end_url: ""
    superset_url: ""
    superset_username: ""
    superset_password: ""

# Resources per container
resources:
  backend:
    requests:
      cpu: "300m"
      memory: "1.5Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  websocket:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  workerLong:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"
  workerShort:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"
  scheduler:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "100m"
      memory: "256Mi"
  frontend:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

